"""empty message

Revision ID: 3d93686063c2
Revises: 56457d56ed92
Create Date: 2017-02-18 06:34:31.134000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d93686063c2'
down_revision = '56457d56ed92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    # ### end Alembic commands ###
